# Example GitHub Actions workflow to rewrap SOPS files when .sops.yaml changes
# Save as: .github/workflows/sops-rewrap.yml (optional)

name: SOPS Rewrap

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.sops.yaml'
      - 'env.json'

jobs:
  rewrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install sops and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends sops jq

      # Configure credentials for your KMS provider here if needed
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      - name: Rewrap env.json
        run: |
          if [ -f env.json ]; then
            sops updatekeys env.json
          else
            echo "env.json not found, skipping"
          fi

      - name: Show SOPS metadata (debug)
        run: |
          if [ -f env.json ]; then
            jq '.sops | {kms,gcp_kms,pgp,age,mac,version}' env.json || true
          fi

      # Commit changes if rewrap modified the file
      - name: Commit changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add env.json
            git commit -m "chore(sops): rewrap env.json with updated recipients"
          fi
